name: deploy-dev

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-aws:
    uses: ./.github/workflows/deploy.yml
    with:
      stage: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.envPAT }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.envPAT }}
      COUCH_DB_URL: ${{ secrets.COUCH_DB_URL_PROD }}
      CONTACT_TO_ADDRESS: ${{ secrets.CONTACT_TO_ADDRESS }}
